package main

import (
	"fmt"
	"github.com/bogdan-largeanu/zing/src/cmd"
	"gopkg.in/yaml.v2"
	"io/ioutil"
	"log"
	"os/exec"
	"strings"
)

type AutoGenerated []struct {
	Run struct {
		Key                  string `yaml:"key"`
		Description          string `yaml:"description"`
		Path                 string `yaml:"path"`
		LiteralBlockBashFile string `yaml:"literal_block_bash_file"`
	} `yaml:"run"`
}

func (c *AutoGenerated) readYml() *AutoGenerated {

	yamlFile, err := ioutil.ReadFile("conf.yaml")
	if err != nil {
		log.Printf("yamlFile.Get err   #%v ", err)
	}
	err = yaml.Unmarshal(yamlFile, c)
	if err != nil {
		log.Fatalf("Unmarshal: %v", err)
	}

	return c
}

func runBash(command string) {
	//app := "echo hello dork"
	shell := "bash"

	shCommand := exec.Command(shell, "-c", command)
	stdout, err := shCommand.Output()

	if err != nil {
		fmt.Println(err.Error())
		return
	}

	fmt.Print(string(stdout))
}

func main() {
	var c AutoGenerated
	c.readYml()
	fmt.Printf("%+v\n", c)
	literalBlockBashFile := c[0].Run.LiteralBlockBashFile
	//fmt.Println("Wasabi: "+ literalBlockBashFile)
	arrayOfBashCommands := strings.Split(literalBlockBashFile, "\n")

	//for i, command := range arrayOfBashCommands {
	//	println(i, command)
	//}

	//modules.WriteYml()
	runBash(arrayOfBashCommands[0])

	//	rootCmd.Execute()
	cmd.Execute()
}
